### Anotações de aula - aula 2

In [1]:
# começando a partir do meio da aula 2. aula 1 foi introdução ao numpy
import numpy as np

In [2]:
x = np.arange(18).reshape(3,6) #vetor range de 0 a 17 reshaped para uma matriz 3x6
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [3]:
#máscara booleana
mask = (x > 7) #retorna true e false para as comparações
print(mask)

[[False False False False False False]
 [False False  True  True  True  True]
 [ True  True  True  True  True  True]]


In [4]:
#somente os valures que passaram na máscara
print(x[mask])

[ 8  9 10 11 12 13 14 15 16 17]


In [5]:
#modificando valores que passaram na mascara
x[mask]=0
print(x)

[[0 1 2 3 4 5]
 [6 7 0 0 0 0]
 [0 0 0 0 0 0]]


In [6]:
x

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
x = np.random.randint(0,10,18).reshape(3,6) #entre 0 e 10 18 n rand
print(x)

[[5 7 8 2 4 1]
 [5 9 2 3 4 7]
 [1 9 4 7 4 4]]


In [16]:
y = np.copy(x[1:,:3]) #forma de fazer slice no x sem continuar apontando para o msm obj
print(y)

[[5 9 2]
 [1 9 4]]


In [17]:
y[1,1] = -1
print(x) #não alterou o objeto inicial, pois utilizou-se o copy

[[5 7 8 2 4 1]
 [5 9 2 3 4 7]
 [1 9 4 7 4 4]]


In [18]:
z = x[1:,:3] #sem utilizar o copy
print(x.data)
print(y.data)
print(z.data)

### Exercícios

### Exercício 1
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [21]:
#1
x = np.random.randint(0,20,30)
A = x.reshape(5,6)
print(A)

[[14 16  8  9  3 11]
 [14 12  3  3  2 16]
 [ 9 16  3 16 10 15]
 [ 4 10  2  7  9  8]
 [ 9 19  3 16 15 18]]


### Exercício 2
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [24]:
#2
view1 = A[[0,1,3],]
view2 = A[1:3,[0,2,4]]
view3 = A[[1,3],[1,3]]
print(view1)
print(view2)
print(view3)

[[14 16  8  9  3 11]
 [14 12  3  3  2 16]
 [ 4 10  2  7  9  8]]
[[14  3  2]
 [ 9  3 10]]
[12  7]


### Exercício 3
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [29]:
#3
A = np.random.randint(0,20,30).reshape(5,6)
Ac = np.copy(A)

mask = (A > 10)
mask2 = ((Ac > 7) & (Ac < 15)) # & and, | or

A[mask] = -1
Ac[mask2] = -1

print(A)
print(Ac)

[[-1  0 -1  4 10 -1]
 [ 3 -1  6  9 -1 -1]
 [ 2  6  6  0  0 10]
 [-1 -1 -1 -1  9  3]
 [ 3  7  2  1  7 10]]
[[17  0 -1  4 -1 -1]
 [ 3 -1  6 -1 16 19]
 [ 2  6  6  0  0 -1]
 [-1 19 -1 19 -1  3]
 [ 3  7  2  1  7 -1]]


### Exercício 4
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [ ]:
#4
A = np.arange(1,201,1).reshape(20,10)

l_odd = []
c_even = []

for i,a in enumerate(A):
    for j,b in enumerate(a):
        if j % 2 != 0 and i == 0:
            c_even.append(j)
    if i % 2 == 0:
        l_odd.append(i)

print(l_odd)
print(c_even)

A_lpares = A[l_odd,]
A_lpares_cimpares = A[l_odd,:][:,c_even]

print(A_lpares)
print(A_lpares_cimpares)

#rows, col = np.indices(a.shape)
#mask_lapares = (rows % 2 == 0) | (col % 2 == 0)

### Exercício 5
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [57]:
#5
A = np.arange(1,201,1).reshape(20,10)

#boolean mask for rows and columns
A_lodd = (np.arange(A.shape[0]) % 2 == 0)
A_codd = (np.arange(A.shape[1]) % 2 == 0)

#boolean mask for the matrix
A_lcodd = np.ix_(A_lodd,A_codd)

print(A[A_lcodd])

[[  1   3   5   7   9]
 [ 21  23  25  27  29]
 [ 41  43  45  47  49]
 [ 61  63  65  67  69]
 [ 81  83  85  87  89]
 [101 103 105 107 109]
 [121 123 125 127 129]
 [141 143 145 147 149]
 [161 163 165 167 169]
 [181 183 185 187 189]]


### Exercício 6
Considere o array `X` de números tipo float gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [70]:
#6
X = np.random.uniform(0.0,1.0,10) #distribuição uniforme entre 0 e 1 randômica
X_sorted = np.sort(X)
print(X_sorted)
print(X_sorted[:3])

[0.05010947 0.16158965 0.27099475 0.3742663  0.40465801 0.61818183
 0.62903116 0.69263381 0.72467902 0.9668606 ]
[0.05010947 0.16158965 0.27099475]


### Exercício 7
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [86]:
#7
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

def troca_colunas(X,i:int,j:int):
    r_shape_zeros = np.zeros(X.shape[0])
    c_size = X.shape[1]
    X = np.hstack((X,r_shape_zeros.reshape(-1,1))) #reshape calculating -1 term and seting 1 column

    column1 = X[:,i:i+1]
    column2 = X[:,j:j+1]

    X_temp = np.copy(X)
    X_temp[:,i:i+1] = column2
    X_temp[:,j:j+1] = column1

    X = X_temp[:,:c_size]

    return X

result = troca_colunas(X,1,4)
print(result)

[[0. 4. 2. 3. 1. 5.]
 [0. 4. 2. 3. 1. 5.]
 [0. 4. 2. 3. 1. 5.]]


### Exercício 8
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [96]:
#8
A =  np.array([[2, 8, 3, 4, 8],
               [4, 8, 7, 7, 3],
               [8, 2, 3, 1, 4],
               [8, 6, 3, 8, 1],
               [6, 4, 4, 6, 1]])

if A.shape[0] == A.shape[1]:
    I = np.identity(A.shape[0])

for i,a in enumerate(I):
    for j,b in enumerate(a):
        if j >= i:
          I[i,j] = 1
        else:
          I[i,j] = 0

#print(I)
print(np.multiply(A,I))


[[2. 8. 3. 4. 8.]
 [0. 8. 7. 7. 3.]
 [0. 0. 3. 1. 4.]
 [0. 0. 0. 8. 1.]
 [0. 0. 0. 0. 1.]]
