### Anotações de aula - aula 3

In [1]:
import numpy as np

In [ ]:
np.array_equal(A,B) #retorna True or False

# (A == b) compara elemento a elemento e cria uma máscara booleana

In [7]:
A = np.zeros((5,5))
A[:] = np.arange(5)

print(A)

print('soma de todos os valores: ', np.sum(A))
print('soma valores das colunas: ', np.sum(A, axis=0)) #axis 0 - colunas
print('soma valores das linhas: ', np.sum(A, axis=1)) #axis 1 - linhas

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
soma de todos os valores:  50.0
soma valores das colunas:  [ 0.  5. 10. 15. 20.]
soma valores das linhas:  [10. 10. 10. 10. 10.]


In [11]:
A = np.random.randint(low=0,high=30,size=(5,5))
A

array([[24, 21, 24, 23,  9],
       [13, 11, 12, 11, 12],
       [11,  1, 27,  7, 27],
       [10,  3, 13,  2, 27],
       [19, 11, 14, 17, 27]])

In [12]:
# todos os el.
print('maior valor na matriz',np.max(A))
print('posicao do maior valor da matriz', np.argmax(A)) #lineariza a matriz A A.ravel

maior valor na matriz 27
posicao do maior valor da matriz 12


In [15]:
# coluna / linhas
print('maior valor em cada coluna', np.max(A, axis=0)) #maior valor de cada coluna
print(np.argmax(A,axis=0))
print('maior valor de cada linha', np.max(A, axis=1)) #... linha
print(np.argmax(A,axis=1))

maior valor em cada coluna [24 21 27 23 27]
[0 0 2 0 2]
maior valor de cada linha [24 13 27 27 27]
[0 0 2 4 4]


In [16]:
A = np.random.randint(0,30,size=(5,5)).astype(float)
print(A)

[[22.  2. 23. 21. 20.]
 [23. 21.  0. 12.  0.]
 [10. 20. 29.  0. 24.]
 [25. 12. 21. 12.  2.]
 [ 9. 23.  3. 24. 22.]]


In [22]:
print('média', np.mean(A))
print('média por coluna', np.mean(A, axis=0))
print('média por linha', np.mean(A, axis=1))

print('mediana', np.median(A))

print('desvio padrão', np.std(A))
print('desvio padrão colunas', np.std(A, axis=0))


média 15.2
média por coluna [17.8 15.6 15.2 13.8 13.6]
média por linha [17.6 11.2 16.6 14.4 16.2]
mediana 20.0
desvio padrão 9.273618495495704
desvio padrão colunas [ 6.85273668  7.76144316 11.53082824  8.4        10.38460399]


In [24]:
A = np.arange(25).reshape(5,5)

M = A > 0

print('>0 ', M)
print('todos os elementos são True?', np.all(M))
print('algum elemento é True?', np.any(M))

>0  [[False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
todos os elementos são True? False
algum elemento é True? True


In [ ]:
A.sort() #modifica o array original
A = np.sort(A) #cria outro array sortido