### Anotações de aula

In [1]:
# começando a partir do meio da aula 2. aula 1 foi introdução ao numpy
import numpy as np

In [2]:
x = np.arange(18).reshape(3,6) #vetor range de 0 a 17 reshaped para uma matriz 3x6
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [3]:
#máscara booleana
mask = (x > 7) #retorna true e false para as comparações
print(mask)

[[False False False False False False]
 [False False  True  True  True  True]
 [ True  True  True  True  True  True]]


In [4]:
#somente os valures que passaram na máscara
print(x[mask])

[ 8  9 10 11 12 13 14 15 16 17]


In [5]:
#modificando valores que passaram na mascara
x[mask]=0
print(x)

[[0 1 2 3 4 5]
 [6 7 0 0 0 0]
 [0 0 0 0 0 0]]


In [6]:
x

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [9]:
x = np.random.randint(0,10,18).reshape(3,6) #entre 0 e 10 18 n rand
print(x)

[[2 8 7 9 0 2]
 [1 4 2 1 4 5]
 [8 8 2 4 5 5]]


In [10]:
y = np.copy(x[1:,:3]) #forma de fazer slice no x sem continuar apontando para o msm obj
print(y)

[[1 4 2]
 [8 8 2]]


In [11]:
y[1,1] = -1
print(x) #não alterou o objeto inicial, pois utilizou-se o copy

[[2 8 7 9 0 2]
 [1 4 2 1 4 5]
 [8 8 2 4 5 5]]
